### PR TITLE
Number Check & Profile Photo Get Added

### PR DESCRIPTION
**Pull request by naveenrao2k**
### **Rationale**
There is no endpoint in the API to check the number before sending & to get the profile photo which is not have any sense but added😅 . I hope it is relevant to you!

## Profile URL Get

http://127.0.0.1:8000/check/photo/{sessionID}/{phoneNumber}

```javascript

{
	success: true|false, // bool
	message: "" | "Account Image not set", // string
	data: { img : "URL"} | {} // string
}

```

## WA Number Check

http://127.0.0.1:8000/check/number/{sessionID}/{phoneNumber}

```javascript

{
	success: true|false, // bool
	message: "Number found" | "The whatsapp number is not exists.", // string
	data: {} // string
}

```

### Changes:
controllers/checkController.js -> Add new Controller.
routes/checkRoute.js -> Add new GET method for check number & to get photo.
whatsapp.js -> I have no idea. In fact, it is my first node project, and I tried to code according to the general structure😅.

### Notes
Please help me improve this PR.

### CODE REVIEW

**Comment by ookamiiixd** [comment]
That's absolutely okay, i'll review it later when i'm free.

**Comment by mdestafadilah** [comment]
> That's absolutely okay, i'll review it later when i'm free.

any help bro?

**Review by OussamaToumirt — APPROVED** [review]

**Comment by luispimenta** [comment]
seems very good

**Review by luispimenta — APPROVED** [review]
great function

**Comment by ookamiiixd** [comment]
I'm sorry but since i've started a complete rewrite of this repo, this PR is definitely gonna conflict with that. I will close this PR, but don't worry, i'll add this feature in the rewritten version.

**Comment by naveenrao2k** [comment]
Ok no problem 🤗

**Pull request closed without merging**
