### PR TITLE
Adding Dockerfile

### PR DESCRIPTION
**Pull request by 4RSIM3R**
Hello

I just adding `Dockerfile` to make people more easy to run this REST-API maybe in future the owner want host an official image of this api

### CODE REVIEW

**Comment by ookamiiixd** [comment]
Hello, can you update the PR into the latest version?

**Comment by 4RSIM3R** [comment]
Sure I can, but unfortunately, my branch has a conflict because I modified it to match my needs how if I past `Dockerfile` and `docker-compose`  here?

**Comment by ookamiiixd** [comment]
Maybe create a new PR? Of course a bare bone Docker config is enough. I've never used Docker before, so i couldn't done this myself

**Comment by 4RSIM3R** [comment]
You can make `Dockerfile` please add this code  : 

```Dockerfile
FROM node:18.12-slim

WORKDIR /app

COPY package.json package-lock*.json ./

RUN npm install && npm cache clean --force

COPY . .

CMD [ "npm", "start" ]
```

and the `docker-compose.yml` : 

```yml
version: "3"

services:
  api:
    image: ilzam/baileys-api:1.0.0
    container_name: "api"
    env_file:
      - .env
    ports:
      - 3000:3000
```

**Comment by ookamiiixd** [comment]
Alright then, thanks for your help. Closing this

**Comment by catursawahlunto** [comment]
not everyone likes and use a docker. for example me. so it's not very useful.

**Pull request closed without merging**
