### PR TITLE
Rewrite the entire thing

### PR DESCRIPTION
**Pull request by ookamiiixd**

### CODE REVIEW

**Comment by luispimenta** [comment]
Hello @ookamiiixd  when will you review this pr?

**Comment by ookamiiixd** [comment]
> Hello @ookamiiixd when will you review this pr?

This PR is the starting point of the complete rewrite of this repo, this will get merged when Baileys v5.0.0 is out and everything is considered stable

**Comment by zahmadz** [comment]
> > Hello @ookamiiixd when will you review this pr?
> 
> This PR is the starting point of the complete rewrite of this repo, this will get merged when Baileys v5.0.0 is out and everything is considered stable

v5 is out now :D

by looking at the commits you made, so now this project will use typescript right?

**Comment by ookamiiixd** [comment]
> > > Hello @ookamiiixd when will you review this pr?
> > 
> > 
> > This PR is the starting point of the complete rewrite of this repo, this will get merged when Baileys v5.0.0 is out and everything is considered stable
> 
> v5 is out now :D
> 
> by looking at the commits you made, so now this project will use typescript right?

Yes, this project has been rewritten entirely with TS. Hope i can prepare for the release this weekend.

**Pull request merged**
